version: '3.4'

services:
  nodepki:
    image: adito/nodepki-docker:production
    restart: unless-stopped
    env_file:
      - .env
    environment:
      TZ: America/New_York
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:$${CA_WEBCLIENT_SERVER_PORT} || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - /opt/data/nodepki:/opt/nodepki/data
      - /opt/data/nodepki-client:/opt/nodepki-client/data
      - /opt/data/nodepki-webclient:/opt/nodepki-webclient/data
      - /opt/data/nodepki-certs:/opt/nodepki-client/out
    extra_hosts:
      - ${CA_API_SERVER_URL}:127.0.0.1
